"""Diagnostic report on Azure PdM windows.

Emits:
- diagnostics/azure_window_horizon_vs_events.png
- diagnostics/azure_windows_summary.md

Illustrates coverage (fraction of failure/control windows with >=1 event)
and mean event count per horizon, and includes 10 random per-machine
spot-checks (raw event stream vs pre-failure 24h window)."""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DIAG = ROOT / "diagnostics"
DIAG.mkdir(exist_ok=True)

events = pd.read_parquet(ROOT / "data" / "processed" / "azure_events.parquet")
windows = pd.read_parquet(ROOT / "data" / "processed" / "azure_windows.parquet")

# Order horizons meaningfully
ORDER = ["1h", "6h", "24h", "last5", "last10"]
w = windows.copy()
w["horizon"] = pd.Categorical(w["horizon"], categories=ORDER, ordered=True)

# ---- Figure 1: coverage + mean event count per horizon ----
fig, axes = plt.subplots(1, 2, figsize=(11, 4.5), constrained_layout=True)

for ax, metric, ylabel, title in [
    (axes[0],
     lambda g: (g["n_events"] > 0).mean(),
     "fraction of windows with >= 1 event",
     "Coverage per horizon"),
    (axes[1],
     lambda g: g["n_events"].mean(),
     "mean events per window",
     "Mean event count per horizon"),
]:
    grouped = w.groupby(["horizon", "is_failure"], observed=True).apply(metric).unstack()
    grouped.columns = ["control", "failure"]
    grouped = grouped.reindex(ORDER)
    x = np.arange(len(ORDER))
    ax.bar(x - 0.18, grouped["control"], width=0.35, label="control", color="#7fb3d5")
    ax.bar(x + 0.18, grouped["failure"], width=0.35, label="failure", color="#d98880")
    ax.set_xticks(x)
    ax.set_xticklabels(ORDER)
    ax.set_ylabel(ylabel)
    ax.set_title(title)
    ax.legend()

fig.suptitle("Azure PdM: pre-failure vs matched-control window coverage", y=1.03)
fig.savefig(DIAG / "azure_window_horizon_vs_events.png", dpi=140, bbox_inches="tight")
print(f"Wrote {DIAG / 'azure_window_horizon_vs_events.png'}")

# ---- Markdown summary ----
lines = []
lines.append("# Azure PdM window sampler diagnostics\n")
lines.append("Generated by `scripts/diagnose_azure_windows.py`.\n")
lines.append("## Coverage summary\n")
tbl = w.groupby(["horizon", "is_failure"], observed=True).agg(
    n_windows=("n_events", "size"),
    frac_nonempty=("n_events", lambda s: float((s > 0).mean())),
    mean_events=("n_events", "mean"),
    median_events=("n_events", "median"),
    max_events=("n_events", "max"),
).round(3)
lines.append(tbl.to_markdown())
lines.append("")
lines.append("### Observation\n")
lines.append("Time horizons of **1h and 6h leave 99.6% and 98% of failure\n"
             "windows empty**. Effectively no Azure PdM failure is preceded\n"
             "by an event in the same hour. Useful horizons are 24h and the\n"
             "count-based (last-5 / last-10) windows.\n\n"
             "Even at 24h, failure and control windows separate cleanly by\n"
             "raw event count alone (failure mean 1.58 vs control 0.077),\n"
             "so the event-count baseline is expected to be strong. Any\n"
             "later claim that itemset or sequence mining helps must beat\n"
             "that baseline on the same split.\n")

lines.append("## 10 random per-machine spot-checks (24h horizon)\n")
sample_ids = pd.Series(events["entity_id"].unique()).sample(10, random_state=7).tolist()
for eid in sorted(sample_ids):
    fw = w[(w["entity_id"] == eid) & (w["horizon"] == "24h") & (w["is_failure"])]
    if fw.empty:
        lines.append(f"### Machine {eid}: no failures observed\n")
        continue
    row = fw.iloc[0]
    lines.append(f"### Machine {eid} - first failure @ {row['anchor']} (target {row['target_failure_type']})\n")
    lines.append(f"Window: `{row['window_start']}` -> `{row['window_end']}` ({row['n_events']} events)\n")
    lines.append("```")
    for et, st in zip(row["event_type_seq"], row["event_subtype_seq"]):
        lines.append(f"  {et:<22s} {st}")
    lines.append("```\n")

(DIAG / "azure_windows_summary.md").write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {DIAG / 'azure_windows_summary.md'}")
